(()=>{
 'use strict';
 const URL='https://raw.githubusercontent.com/wreed1989/SpaceWxOps-WXF/main/chhss-data/huxt-forecast.json';
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const utc=x=>Number.isFinite(Date.parse(x))?new Date(x).toISOString().replace('T',' ').slice(0,16)+' UTC':'Unavailable';
 function valid(d){return d?.schemaVersion==='wxf-huxt-1'&&Number.isFinite(Date.parse(d.issuedAt))&&(d.status==='withheld'||d.status==='experimental'&&d.rows?.length>100&&d.rows.every((r,i)=>Number.isFinite(Date.parse(r.time))&&(!i||Date.parse(r.time)>Date.parse(d.rows[i-1].time))&&['ambientSpeed','cmeSpeed'].every(k=>Number.isFinite(r[k])&&r[k]>0&&r[k]<3500)));}
 let saved=null;try{const d=JSON.parse(document.getElementById('huxtBootstrap')?.textContent||'null');if(valid(d))saved=d;}catch(_){}
 function chart(d){const x=d.rows.map(r=>r.time),max=Math.max(700,...d.rows.map(r=>r.cmeSpeed))*1.12;
  return{traces:[['ambientSpeed','WSA ambient','#62d5cf'],['cmeSpeed','WSA + DONKI CMEs','#ffbd7c']].map(([key,name,color])=>({name,x,y:d.rows.map(r=>r[key]),type:'scatter',mode:'lines',line:{color,width:2,dash:key==='ambientSpeed'?'dot':'solid'},connectgaps:false,hovertemplate:'%{x|%d %b %H:%M UTC}<br>%{y:.0f} km/s<extra>'+name+'</extra>'})),layout:{autosize:true,paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'#0c1c29',font:{color:'#b7cfdf'},margin:{l:60,r:20,t:35,b:45},hovermode:'x unified',hoverlabel:{bgcolor:'#111e2b',font:{color:'#fff'},bordercolor:'#617f98'},legend:{orientation:'h',y:1.13},xaxis:{type:'date',title:'UTC',gridcolor:'#233b4d'},yaxis:{title:'Earth wind speed · km/s',range:[0,max],minallowed:0,gridcolor:'#233b4d'},shapes:[{type:'rect',xref:'x',yref:'paper',x0:x[0],x1:d.issuedAt,y0:0,y1:1,fillcolor:'rgba(150,160,170,.10)',line:{width:0},layer:'below'},{type:'line',xref:'x',yref:'paper',x0:d.issuedAt,x1:d.issuedAt,y0:0,y1:1,line:{color:'#acc0d0',dash:'dot',width:1}}],annotations:[{xref:'x',yref:'paper',x:d.issuedAt,y:1,text:'Run issued',showarrow:false,xanchor:'left',font:{size:10,color:'#acc0d0'}}]}};}
 function mount(root){let stopped=false,ctrl=null,render=Promise.resolve();
  async function draw(error=''){
   if(stopped)return;root.querySelectorAll('.js-plotly-plot').forEach(p=>window.Plotly?.purge(p));
   const d=saved;if(!d){root.innerHTML='<h3>WXF local HUXt · Earth time series</h3><p class="wx-status">Numerical run unavailable. '+esc(error)+'</p>';return;}
   if(d.status==='withheld'){root.innerHTML='<h3>WXF local HUXt</h3><p class="wx-status">Run withheld: '+esc(d.reason)+'</p>';return;}
   const stale=Date.now()-Date.parse(d.issuedAt)>3*3600000;
   root.innerHTML=`<h3>WXF local HUXt · Earth time series</h3><p class="wx-status">${stale?'STALE SNAPSHOT':'EXPERIMENTAL'} · Run issued ${utc(d.issuedAt)} · SWPC boundary ${utc(d.boundary?.boundaryEpoch)} · ${d.cmeInputs?.length||0} DONKI cones</p><div data-huxt-plot style="height:340px;min-width:0"></div><p class="wx-status">Numerical HUXt output using SWPC’s processed ambient inner boundary and DONKI CME analyses. Before the dotted line: reconstruction with current inputs. After it: forecast. ${error?esc(error):''}</p><details><summary>Inputs and interpretation</summary><p>Solid: wind including modeled CMEs. Dotted: ambient wind. Identical traces mean no modeled CME contribution along the Earth line. HUXt predicts speed; it does not supply Bz or an electron-flux forecast. This series is recorded for paired historical and future verification before it changes the electron forecast.</p><p>${esc(d.qualification)}</p><p>Assumptions: ${(d.assumptions||[]).map(esc).join(' ')}</p><p><a href="${esc(d.source?.url)}" target="_blank" rel="noopener">SWPC boundary input</a> · <a href="${URL}" target="_blank" rel="noopener">Numerical output</a> · <a href="https://github.com/University-of-Reading-Space-Science/HUXt" target="_blank" rel="noopener">HUXt model</a></p></details>`;
   const p=chart(d);await window.Plotly?.react(root.querySelector('[data-huxt-plot]'),p.traces,p.layout,{responsive:true,scrollZoom:false,displaylogo:false,displayModeBar:false});
  }
  // Let Plotly finish before replacing or purging its target during a fast refresh.
  function paint(error=''){render=render.then(()=>draw(error)).catch(()=>{if(!stopped)root.innerHTML='<h3>WXF local HUXt</h3><p class="wx-status">Plot unavailable. Refresh products to retry.</p>';});return render;}
  async function refresh(){ctrl?.abort();const request=ctrl=new AbortController();const timer=setTimeout(()=>request.abort(),15000);try{const r=await fetch(URL,{signal:request.signal,cache:'no-store',credentials:'omit'});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(!valid(d))throw Error('Invalid numerical run');if(stopped||ctrl!==request)return;if(!saved||Date.parse(d.issuedAt)>=Date.parse(saved.issuedAt))saved=d;window.SpaceWxHeaderStatus?.report('huxt','HUXt numerical publication',d.status==='experimental'&&Date.now()-Date.parse(d.issuedAt)<=3*3600000,d.reason||'Run issued '+utc(d.issuedAt));await paint();}catch(e){if(!stopped&&ctrl===request){window.SpaceWxHeaderStatus?.report('huxt','HUXt numerical publication',false,e.message);await paint('Refresh unavailable; retaining dated run.');}}finally{clearTimeout(timer);}}
  paint();return{refresh,stop(){stopped=true;ctrl?.abort();const plots=[...root.querySelectorAll('.js-plotly-plot')];render.then(()=>plots.forEach(p=>window.Plotly?.purge(p)));}};
 }
 window.SpaceWxLocalHUXt={mount,chart,valid};
})();
