/* Generated by sharp_mag_pipeline.py; replace at each formal 21Z cycle. */
window.FLARE_GUIDANCE_PAYLOAD = {
  "schema_version": "4.1",
  "model_version": "sharp-mag-20260822-hierx1",
  "script_version": "1.3.0",
  "operational": false,
  "probability_scale": "percent",
  "issued": "2026-08-22T17:25:33Z",
  "valid_start": "2026-08-23T00:00:00Z",
  "valid_end": "2026-08-24T00:00:00Z",
  "quality": {
    "level": "research",
    "message": "Daily SHARP-MAG inference from a saved calibrated M1+ model and a hierarchical X1+ severity layer. Research/shadow guidance unless explicitly validated and marked operational."
  },
  "input": {
    "series": "hmi.sharp_cea_720s_nrt",
    "target_time": "2026-08-22T14:25:33Z",
    "latest_record": "2026-08-22T14:24:00Z",
    "oldest_retained_record": "2026-08-22T14:24:00Z",
    "raw_records": 2427,
    "retained_regions": 2,
    "mapping": {
      "skipped_multi_region_harps": 0,
      "skipped_unmapped_harps": 16,
      "expanded_rows": 5
    },
    "quality": {
      "input": 5,
      "rejected_longitude": 3,
      "after_longitude": 2,
      "quality_missing": 0,
      "quality_top_values": {
        "0x00000400": 2
      },
      "rejected_quality": 0,
      "after_quality": 2,
      "rejected_harp_merge": 0,
      "after_harp_merge": 2,
      "rejected_observer_velocity": 0,
      "after_observer_velocity": 2,
      "rejected_missing_mapping": 0,
      "after_mapping": 2,
      "min_finite_parameters": 12,
      "rejected_parameter_completeness": 0,
      "after_parameter_completeness": 2,
      "retained": 2
    }
  },
  "regions": [
    {
      "id": "full-disk",
      "label": "Full Disk",
      "quality": {
        "level": "research",
        "message": "Visible-disk SHARP-MAG combination of quality-controlled, single-region HARPs. It contains no residual term for unnumbered, farside, or excluded limb regions."
      },
      "drivers": [
        "2 active regions represented",
        "Regional probabilities combined as 1 - product(1 - p_i)",
        "No unnumbered/farside residual term"
      ],
      "members": {
        "sharpmag": {
          "m1": 38.8,
          "x1": 2.4,
          "source": "SHARP-MAG sharp-mag-20260822-hierx1 regional combination",
          "quality": "research"
        }
      }
    },
    {
      "id": "AR14511",
      "label": "AR 14511",
      "location": "",
      "mcintosh": "",
      "quality": {
        "level": "research",
        "message": "SHARP NRT record age 3.0 h; single-region HARP; |LON_FWT|=37.3\u00b0"
      },
      "members": {
        "sharpmag": {
          "m1": 0.0,
          "x1": 0.0,
          "source": "SHARP-MAG sharp-mag-20260822-hierx1 (calibrated M1; hierarchical X1)",
          "quality": "research"
        }
      },
      "drivers": [
        "M1+: lower strong-gradient PIL flux",
        "M1+: falling strong-gradient PIL flux",
        "M1+: lower mean magnetic shear",
        "X1+: hierarchical severity factor 6.1% of SHARP M1+"
      ]
    },
    {
      "id": "AR14513",
      "label": "AR 14513",
      "location": "",
      "mcintosh": "",
      "quality": {
        "level": "research",
        "message": "SHARP NRT record age 3.0 h; single-region HARP; |LON_FWT|=42.2\u00b0"
      },
      "members": {
        "sharpmag": {
          "m1": 38.8,
          "x1": 2.4,
          "source": "SHARP-MAG sharp-mag-20260822-hierx1 (calibrated M1; hierarchical X1)",
          "quality": "research"
        }
      },
      "drivers": [
        "M1+: lower total free-energy proxy",
        "M1+: elevated total unsigned vertical current",
        "M1+: elevated strong-gradient PIL flux",
        "X1+: hierarchical severity factor 6.1% of SHARP M1+"
      ]
    }
  ]
};
