/* Solar Flare: coordinated observations, immutable model provenance, no browser fusion. */
(function(){
'use strict';
const FEED='https://raw.githubusercontent.com/wreed1989/SpaceWxOps-WXF/flare-live/';
const E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const N=x=>x===null||x===undefined||x===''?null:Number.isFinite(Number(x))?Number(x):null;
const A=x=>Array.isArray(x)?x:[];
function time(x){if(!x)return NaN;const t=String(x);return Date.parse(/^\d{4}-\d\d-\d\d(?:[ T]\d\d:\d\d(?::\d\d(?:\.\d+)?)?)?$/.test(t)?t.replace(' ','T')+(t.length===10?'T00:00:00Z':'Z'):t);}
function date(x){const t=time(x);return Number.isFinite(t)?new Date(t).toISOString().slice(0,16).replace('T',' ')+' UTC':'Unavailable';}
function num(x,d=1){x=N(x);return x===null?'—':Math.abs(x)>=1e5||Math.abs(x)>0&&Math.abs(x)<.01?x.toExponential(2):x.toLocaleString('en-US',{maximumFractionDigits:d});}
function percent(x){return N(x)===null?'—':num(x,1)+'%';}
function region(x){const n=parseInt(String(x??'').replace(/\D/g,''),10);return Number.isFinite(n)&&n>0?'AR'+(n<10000?n+10000:n):null;}
function fresh(x,h=36){const t=time(x);return Number.isFinite(t)&&Date.now()-t<=h*3600000&&t<=Date.now()+300000;}
function safeAsset(path){if(typeof path!=='string'||path.includes('..')||!/^images\/[a-z0-9/_\-.]+$/i.test(path))return '';return FEED+path;}
const channelNames={continuum:'HMI Continuum',magnetogram:'HMI Magnetogram',aia171:'AIA 171 Å'};
let data=null,esa=null,pending=null,checked=0,error='',scheduled=0,loop=0,frameIndex=-1,mode='pair',zoom=1,lastRegion='';
const snapshot=()=>window.__SPACEWXOPS_FLARE_SNAPSHOT__||{};
const selected=()=>document.getElementById('flareGuidanceRegion')?.value||snapshot().selectedId||'full-disk';
function currentRegions(){
 const forecast=new Map(A(snapshot().regions).map(x=>[x.id,x]));
 let rows=A(snapshot().solarRegions),latest=rows.map(r=>r.observedDate||'').sort().at(-1)||'';
 if(!rows.length&&data){rows=A(data.regions).map(r=>({...r,observedDate:r.observed_date,mcintosh:r.spot_class,magnetic:r.mag_class,spots:r.number_spots,carringtonLongitude:r.carrington_longitude}));latest=rows.map(r=>r.observedDate).sort().at(-1)||'';}
 return rows.filter(r=>r.observedDate===latest&&region(r.region)&&N(r.longitude)!==null&&Math.abs(N(r.longitude))<=90).map(r=>({...r,id:region(r.region),forecast:forecast.get(region(r.region))})).sort((a,b)=>Number(a.longitude)-Number(b.longitude));
}
function modelInput(id){return A(data?.model?.regions).find(r=>region(r.NOAA_REGION)===id)||null;}
function modelMember(id){const s=snapshot();if(s.model?.generationStatus?.used_previous_forecast)return null;const r=A(s.regions).find(r=>r.id===id),m=r?.members?.sharpmag;
 if(!m||!fresh(m.issued||s.issued,36)||!Number.isFinite(time(m.validEnd||s.validEnd))||time(m.validEnd||s.validEnd)<=Date.now()||/stale/i.test(JSON.stringify(m.quality||s.model?.quality||'')))return null;
 return m;
}
function latestFrame(key='continuum'){return A(data?.imagery?.channels?.[key]).at(-1)||null;}
function product(key){const p=esa?.products?.[key];return p&&!/unavailable|failed/i.test(p.status||'')?p:null;}
function selectRegion(id){const s=document.getElementById('flareGuidanceRegion');if(!s)return;
 if(!Array.from(s.options).some(o=>o.value===id)&&currentRegions().some(r=>r.id===id)){const option=document.createElement('option');option.value=id;option.textContent=id.replace('AR','AR ');s.appendChild(option);}
 if(!Array.from(s.options).some(o=>o.value===id))return;
 s.value=id;s.dispatchEvent(new Event('change',{bubbles:true}));queue();
}
function facts(items){return '<dl class="sf-facts">'+items.map(([k,v,title])=>`<div${title?` title="${E(title)}"`:''}><dt>${E(k)}</dt><dd>${E(v)}</dd></div>`).join('')+'</dl>';}
function table(headers,rows,empty='Unavailable'){return rows.length?`<div class="sf-table-scroll"><table><thead><tr>${headers.map(x=>`<th>${E(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:`<div class="sf-empty">${E(empty)}</div>`;}
function style(){if(document.getElementById('sfWorkspaceStyle'))return;const s=document.createElement('style');s.id='sfWorkspaceStyle';s.textContent=`
.sf-workspace{--sf-line:var(--fd-line,rgba(140,168,188,.22));--sf-muted:var(--fd-muted,#92aabc);--sf-panel:var(--fd-panel,rgba(10,23,35,.32));color:inherit;min-width:0}
.sf-top{display:grid;grid-template-columns:minmax(290px,.72fr) minmax(380px,1.28fr);gap:16px;align-items:start}.sf-workspace #fdFlareGuidanceSlot,.sf-workspace #fdSunspotBrowser,.sf-pane{min-width:0;margin:0!important;border:1px solid var(--sf-line);border-radius:12px;background:var(--sf-panel);padding:14px}
.sf-workspace #fdFlareAnalysis{margin-top:16px;background:transparent;border:0;padding:0}.sf-workspace .fd-flare-live-guidance{margin:0;padding:0}.sf-workspace .fd-flare-live-guidance #flareGuidanceValid,.sf-workspace .fd-flare-live-guidance #flareGuidanceFooter{display:none!important}
.sf-workspace h3{font-size:15px;margin:0 0 12px}.sf-workspace h4{font-size:13px;margin:0 0 8px}.sf-workspace p{line-height:1.45}.sf-muted,.sf-workspace small{color:var(--sf-muted);font-size:12px}.sf-overview{display:grid;grid-template-columns:minmax(130px,.7fr) minmax(165px,1fr);gap:12px;align-items:start}.sf-disk{position:relative;width:min(100%,270px);aspect-ratio:1;margin:auto}.sf-disk img{width:100%;height:100%;object-fit:contain;border-radius:7px}.sf-disk button{position:absolute;transform:translate(-50%,-50%);border:1px solid #88daf9;background:#101d2edb;color:#fff;border-radius:12px;padding:2px 5px;font-size:10px;cursor:pointer}.sf-disk button[aria-pressed=true]{background:#087ea4}
.sf-regions{display:grid;grid-template-columns:repeat(auto-fit,minmax(142px,1fr));gap:6px;max-height:290px;overflow:auto}.sf-region{padding:9px!important;display:grid;gap:4px;text-align:left!important;border:1px solid var(--sf-line)!important;border-radius:8px;background:transparent!important;color:inherit;cursor:pointer}.sf-region[aria-pressed=true]{border-color:#62c9ea!important;background:#2886b01c!important}.sf-region strong{font-size:13px}.sf-region span,.sf-region small{font-size:11px}.sf-empty{display:flex;align-items:center;justify-content:center;min-height:90px;padding:16px;color:var(--sf-muted);text-align:center}
.sf-analysis-grid{display:grid;grid-template-columns:minmax(360px,1.2fr) minmax(290px,1fr);gap:16px;align-items:start}.sf-heading{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-bottom:12px}.sf-heading h3{margin:0}.sf-controls{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.sf-controls select,.sf-controls button,.sf-workspace button.sf-button{font:inherit;color:inherit;background:var(--sf-panel);border:1px solid var(--sf-line);border-radius:6px;padding:5px 8px;cursor:pointer}.sf-controls select{max-width:180px}.sf-controls input[type=range]{flex:1;min-width:100px}.sf-images{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.sf-images.single{grid-template-columns:minmax(0,1fr)}.sf-images figure{margin:0;min-width:0}.sf-image-box{height:clamp(220px,27vw,360px);overflow:hidden;background:#080b10;border-radius:7px}.sf-images img{width:100%;height:100%;object-fit:contain;display:block;transform:scale(var(--sf-zoom,1));transform-origin:center}.sf-images figcaption{font-size:11px;line-height:1.5;padding:6px 0;overflow-wrap:anywhere}.sf-image-status{font-size:11px;color:var(--sf-muted);margin:4px 0 10px;min-height:16px}.sf-facts{display:grid;grid-template-columns:repeat(auto-fit,minmax(105px,1fr));gap:10px;margin:10px 0 14px}.sf-facts div{min-width:0}.sf-facts dt{font-size:11px;color:var(--sf-muted);margin-bottom:5px}.sf-facts dd{margin:0;font-size:14px;overflow-wrap:anywhere}.sf-facts .sf-number{font-size:20px}
.sf-workspace details{border-top:1px solid var(--sf-line);padding:10px 0}.sf-workspace summary{cursor:pointer;font-size:13px;list-style-position:inside}.sf-workspace details>div{margin-top:10px}.sf-workspace details p{font-size:12px}.sf-workspace details:last-child{padding-bottom:0}.sf-table-scroll{max-height:285px;overflow:auto;margin:10px 0}.sf-table-scroll table{width:100%;border-collapse:collapse;font-size:12px}.sf-table-scroll th{position:sticky;top:0;background:var(--sf-panel);text-align:left;font-size:11px}.sf-table-scroll td,.sf-table-scroll th{padding:8px 6px;border-bottom:1px solid var(--sf-line);vertical-align:top}.sf-table-scroll small{display:block;font-size:10px;margin-top:3px}.sf-probabilities{display:grid;grid-template-columns:1fr 1fr;gap:10px}.sf-probabilities div{padding:12px;border:1px solid var(--sf-line);border-radius:8px}.sf-probabilities strong{font-size:24px;display:block;margin-top:5px}.sf-section{margin-top:14px}.sf-status{font-size:11px;padding:4px 7px;border:1px solid var(--sf-line);border-radius:6px;color:var(--sf-muted)}
@media(max-width:1100px){.sf-top{grid-template-columns:minmax(265px,.8fr) minmax(320px,1.2fr)}.sf-analysis-grid{grid-template-columns:minmax(300px,1.1fr) minmax(265px,1fr)}.sf-images{grid-template-columns:1fr}.sf-image-box{height:260px}}
@media(max-width:780px){.sf-top,.sf-analysis-grid{grid-template-columns:minmax(0,1fr)}.sf-images{grid-template-columns:repeat(2,minmax(0,1fr))}.sf-image-box{height:240px}.sf-overview{grid-template-columns:minmax(120px,.65fr) minmax(150px,1fr)}}
@media(max-width:480px){.sf-images,.sf-overview{grid-template-columns:1fr}.sf-disk{max-width:230px}.sf-regions{max-height:200px}.sf-image-box{height:240px}.sf-facts{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(s);}
function syncMarkup(root,markup,signature){if(!root||root.dataset.sfSignature===signature)return false;const opens=Array.from(root.querySelectorAll('details[open]')).map(d=>d.dataset.section);root.innerHTML=markup;root.dataset.sfSignature=signature;for(const k of opens)root.querySelector(`details[data-section="${k}"]`)?.setAttribute('open','');return true;}
function renderBrowser(){style();const root=document.getElementById('fdSunspotBrowser');if(!root)return;const rows=currentRegions(),id=selected(),f=latestFrame(),usable=f&&fresh(f.observed_at,36);const signature=JSON.stringify([id,rows,data?.checked_at,f?.id,error]);
 const disk=usable?`<div class="sf-disk"><img src="${E(safeAsset(f.disk))}" alt="HMI Continuum Full Disk">${rows.map(r=>{const g=f.regions?.[r.id];return g?`<button type="button" data-sf-region="${E(r.id)}" aria-pressed="${r.id===id}" style="left:${(g.x/4096*100).toFixed(3)}%;top:${(g.y/4096*100).toFixed(3)}%" title="${E(r.id+' · '+(r.location||''))}">${E(r.id.slice(3))}</button>`:'';}).join('')}</div>`:'<div class="sf-empty">Imagery Unavailable</div>';
 const cards=[`<button class="sf-region" type="button" data-sf-region="full-disk" aria-pressed="${id==='full-disk'}"><strong>Full Disk</strong><span>${rows.length} Numbered Regions</span><small>WXF M1+ ${percent(modelMember('full-disk')?.m1)}</small></button>`,...rows.map(r=>`<button class="sf-region" type="button" data-sf-region="${E(r.id)}" aria-pressed="${r.id===id}"><strong>${E(r.id.replace('AR','AR '))} · ${E(r.location||'—')}</strong><span>${E(r.mcintosh||'Plage')} · ${E(r.magnetic||'—')}</span><small>WXF M1+ ${percent(modelMember(r.id)?.m1)}</small></button>`)];
 syncMarkup(root,`<div class="sf-heading"><h3>Active Regions</h3><button type="button" class="sf-button" data-sf-refresh title="Refresh Solar Flare Evidence">↻</button></div><div class="sf-overview"><div>${disk}<div class="sf-image-status">${usable?date(f.observed_at):error?'Unavailable':'Loading…'}</div></div><div class="sf-regions">${cards.join('')}</div></div>`,signature);load().catch(()=>{});
}
function diagnostics(){const m=data?.model,db=data?.database,manifest=m?.manifest,report=m?.training_report;if(!m)return '<div class="sf-empty">Model Details Unavailable</div>';
 const detail=[['Model',m.model_version],['Issued',date(m.issued)],['SHARP Record',date(m.stats?.latest_record)],['Fitted Through',db?.fitted_through||'Unavailable'],['Database Through',db?.database_through||'Unavailable'],['Completed New Cases',db?.new_cases??'Unavailable']];
 return facts(detail)+`<p>WXF uses independently calibrated M1+ and X1+ SHARP classifiers. Magnetic state, 24-hour change, disk position and prior regional flare history are model inputs. X1+ is constrained not to exceed M1+.</p><p>The full-disk value combines unique HARP/region components once. It is not separately calibrated; unnumbered/farside residual activity is not modeled. Missing magnetic coverage uses the published, labeled fallback.</p><p>The frozen fit contains 7,706 region-days and 19 X1+ positive days. Only six X1+ positives were in its final test block, so X-class calibration remains uncertain. New observations update the evidence and evaluation database, not the fitted coefficients automatically.</p><p>Solar Demon, SIDC identification and PFSS connectivity are cross-checks, not independent probability multipliers. Provider probabilities are benchmarks, not extra votes. Display imagery is not used to calculate quantitative magnetic flux, helicity, polarity or shear.</p>${db?.forward_check?table(['Post-Training Check','Cases','Events','Brier'],Object.entries(db.forward_check).map(([k,v])=>[E(k),num(v.cases,0),num(v.events,0),num(v.brier,5)])):''}<p>${E(db?.note||'Database update unavailable; the existing fitted model remains unchanged.')}</p>`;
}
function identity(r,input){const id=r.id,sidc=r.forecast?.members?.sidc||A(snapshot().regions).find(x=>x.id===id)?.members?.sidc;
 const c=N(input?.HARP_REGION_COUNT),items=[['NOAA Region',id.replace('AR','AR ')],['NOAA Observed',date(r.observedDate)],['Current McIntosh',r.mcintosh||'Plage'],['At-Issue McIntosh',r.forecast?.mcintosh||'Unavailable'],['Hale Class',r.magnetic||'Unavailable'],['HARP',input?'HARP '+input.HARPNUM:'Unavailable'],['Forecast Issued',date(snapshot().issued)],['Mapping',input?(c>1?'Shared · '+c+' NOAA Regions':'Single NOAA Region'):'No Accepted Magnetic Input'],['SIDC Guidance',sidc?'Same NOAA Identifier':'No Matching Regional Forecast'],['Magnetic Polarity','Inspect Signed HMI Map']];
 const history=A(data?.region_history).filter(x=>region(x.region)===id).sort((a,b)=>String(b.observed_date).localeCompare(String(a.observed_date))).slice(0,5);
 return facts(items)+table(['Observed · UTC','Position','McIntosh / Hale','Area · µHem'],history.map(x=>[E(x.observed_date+' 00:00'),E(x.location),E((x.spot_class||'—')+' / '+(x.mag_class||'—')),num(x.area,0)]))+`<p>Identity matches require the same numbered NOAA region. HARP mappings can cover more than one region. Hale complexity, measured field sign and PFSS footpoint polarity are different quantities; one is not substituted for another.</p>`;
}
function magnetism(input){if(!input)return '<div class="sf-empty">No Accepted SHARP Vector</div>';const change=(a,b)=>N(a)!==null&&N(b)!==null&&N(b)!==0?(100*(Number(a)-Number(b))/Math.abs(Number(b))):null;
 return facts([['Unsigned Flux · Mx',num(input.USFLUX)],['24-Hour Flux Change',percent(change(input.USFLUX,input.PREV_USFLUX))],['R Value',num(input.R_VALUE)],['Mean Shear · °',num(input.MEANSHR)],['Unsigned Current Helicity',num(input.TOTUSJH)],['Free-Energy Proxy',num(input.TOTPOT)]])+`<p class="sf-muted">${date(input.T_REC_UTC)} · ${num(input.SHARP_FINITE_PARAMETER_COUNT,0)}/18 Scalar Parameters · HARP ${num(input.HARPNUM,0)}</p>`+table(['Parameter','Current','Prior Sample'],Object.keys(input).filter(k=>['USFLUX','MEANGBT','MEANJZH','MEANPOT','SHRGT45','TOTUSJH','MEANGBH','MEANALP','MEANGAM','MEANGBZ','MEANJZD','TOTUSJZ','SAVNCPP','TOTPOT','MEANSHR','AREA_ACR','R_VALUE','ABSNJZH'].includes(k)).map(k=>[E(k),num(input[k],3),num(input['PREV_'+k],3)]))+`<h4>Prior Flare History At Issue</h4>`+table(['Input','Value'],[['M1+ · Prior 24 Hours',input.PRIOR_M1_COUNT_24H],['M1+ · Prior 7 Days',input.PRIOR_M1_COUNT_7D],['M1+ · Prior 30 Days',input.PRIOR_M1_COUNT_30D],['X1+ · Prior 7 Days',input.PRIOR_X1_COUNT_7D],['X1+ · Prior 30 Days',input.PRIOR_X1_COUNT_30D],['Hours Since M1+',input.HOURS_SINCE_M1],['Hours Since X1+',input.HOURS_SINCE_X1]].map(([k,v])=>[E(k),num(v,1)]));}
function eventsFor(id){const all=id==='full-disk',goes=A(data?.events).filter(e=>/^[MX]/.test(e.class)&&(all||region(e.region)===id)),d=product('solardemon'),demon=A(d?.events).filter(e=>/^[MX]/.test(e.estimated_class)&&(all||region(e.region)===id));
 const used=new Set(),rows=goes.map(g=>{const matches=demon.filter(e=>region(e.region)===region(g.region)&&region(g.region)&&Math.abs(time(e.peak)-time(g.peak))<=1800000);if(matches.length===1&&goes.filter(h=>region(h.region)===region(matches[0].region)&&Math.abs(time(h.peak)-time(matches[0].peak))<=1800000).length===1)used.add(matches[0]);return [E(date(g.peak)),`<strong>${E(g.class)}</strong><small>GOES X-Ray</small>`,E(region(g.region)?.replace('AR','AR ')||'Unassigned'),matches.length===1&&used.has(matches[0])?`${E(matches[0].estimated_class)} EUV Estimate<small>Solar Demon Time / Region Match</small>`:matches.length>0?'Ambiguous Solar Demon Match':'GOES Report'+(g.reports>1?`<small>${g.reports} Reports Deduplicated</small>`:'')];});
 for(const e of demon)if(!used.has(e))rows.push([E(date(e.peak)),E(e.estimated_class)+'<small>Solar Demon EUV Estimate</small>',E(region(e.region)?.replace('AR','AR ')||'Unassigned'),'No Unique GOES Match']);
 return table(['Peak · UTC','Class','Region','Cross-Check'],rows,data?'No M1+ Events Reported For This Selection':'Unavailable')+`<div class="sf-muted">Solar Demon Processed Through ${date(d?.last_processed_at)}${!d?' · Unavailable':''}</div>`;
}
function connectivity(r){const api=window.SpaceWxSolarEvidence?.api,m=A(product('connectivity')?.models).find(m=>m.body==='EARTH'&&m.footpoints);if(!api||!m)return '<div class="sf-empty">Unavailable</div>';
 const check=api.connectivityCheck({lat:N(r.latitude),lon:N(r.carringtonLongitude),time:r.observedDate},m);
 return (check.available?table(['Earth Trace Scenario','Nearest Footpoint','Weight Within 15°'],check.groups.map(g=>[E(g.group),num(g.nearest)+'°',percent(g.traceShare15)])):`<div class="sf-empty">${E(check.reason)}</div>`)+`<p>PFSS/Parker geometry supports source association. It does not change WXF flare occurrence probability or provide measured photospheric polarity.</p><button type="button" class="sf-button" data-sf-catalog="solar.connectivity">Magnetic Connectivity</button>`;
}
function renderAnalysis(){style();const root=document.getElementById('fdFlareAnalysis');if(!root)return;const id=selected(),r=currentRegions().find(x=>x.id===id),m=modelMember(id),input=r?modelInput(id):null;
 if(lastRegion!==id){stopLoop();frameIndex=-1;lastRegion=id;}
 const signature=JSON.stringify([id,data?.checked_at,error,snapshot().issued,m,r,esa?.checked_at]);
 const type=!m?'Unavailable':id==='full-disk'?'Unique-Component Aggregate':m.method==='sharp_magnetic'?(N(input?.HARP_REGION_COUNT)>1?'Shared HARP Magnetic Classifier':'SHARP Magnetic Classifier'):/fallback/.test(m.method||'')?'Coverage Fallback':'Published WXF';
 const prob=`<div class="sf-heading"><h3>WXF</h3><span class="sf-status">${E(type)}</span></div><div class="sf-probabilities"><div><small>M1+</small><strong>${percent(m?.m1)}</strong></div><div><small>X1+</small><strong>${percent(m?.x1)}</strong></div></div><p class="sf-muted">${date(m?.validStart||snapshot().validStart)} – ${date(m?.validEnd||snapshot().validEnd)}</p>`;
 const details=r?`<details data-section="identity"><summary>Identity &amp; Tracking</summary><div>${identity(r,input)}</div></details><details data-section="magnetic"><summary>Magnetic State &amp; Evolution</summary><div>${magnetism(input)}</div></details><details data-section="events"><summary>GOES / Solar Demon · M1+</summary><div>${eventsFor(id)}</div></details><details data-section="connectivity"><summary>Earth Connectivity Cross-Check</summary><div>${connectivity(r)}</div></details>`:`${facts([['Regions At Issue',data?.model?.full_disk?.numbered_regions??'—'],['Current Regions',currentRegions().length],['SHARP Regions',data?.model?.full_disk?.sharp_regions??'—'],['Fallback Regions',data?.model?.full_disk?.fallback_regions??'—'],['Unique Components',data?.model?.full_disk?.components??'—']])}<details data-section="events"><summary>GOES / Solar Demon · M1+</summary><div>${eventsFor('full-disk')}</div></details>`;
 const imagery=r?`<div class="sf-heading"><h3>${E(id.replace('AR','AR '))} · Region Imagery</h3><div class="sf-controls"><button type="button" data-sf-zoom aria-label="Toggle Region Image Zoom">Zoom ${zoom}×</button><select data-sf-channel aria-label="Region Imagery Channel"><option value="pair">Continuum + Magnetogram</option><option value="continuum">HMI Continuum</option><option value="magnetogram">HMI Magnetogram</option><option value="aia171">AIA 171 Å</option></select></div></div><div data-sf-images></div><div class="sf-controls"><button type="button" data-sf-play aria-label="Play Verified Region Frames">▶</button><input type="range" data-sf-frame aria-label="Verified Region Frame" min="0" max="0" value="0"><span data-sf-frame-count class="sf-muted"></span></div><div data-sf-image-status class="sf-image-status"></div>${facts([['Position',r.location||'—'],['McIntosh',r.mcintosh||'Plage'],['Hale Class',r.magnetic||'—'],['Area · µHem',num(r.area,0)],['Sunspots',num(r.spots,0)]])}<details data-section="imagery"><summary>Image Registration</summary><div><p>Crops retain native pixels from 4096-pixel Helioviewer HMI/AIA images. NOAA Carrington centers are projected with each image’s observer latitude, central longitude and disk geometry. Registration follows a reported region center, not a measured spot boundary. Each channel retains its actual timestamp; missing images are omitted, not interpolated.</p><p>Continuum shows morphology; the signed HMI display supports visual polarity assessment. Color/brightness values are not ingested as quantitative magnetograms.</p></div></details>`:`<h3>Region Coverage</h3>${table(['NOAA Region','McIntosh / Hale','WXF M1+','Magnetic Coverage'],currentRegions().map(x=>{const t=modelInput(x.id),w=modelMember(x.id);return [`<button type="button" class="sf-button" data-sf-region="${E(x.id)}">${E(x.id.replace('AR','AR '))}</button>`,E((x.mcintosh||'Plage')+' / '+(x.magnetic||'—')),percent(w?.m1),t?'HARP '+E(t.HARPNUM)+(N(t.HARP_REGION_COUNT)>1?' · Shared':''):w?'Fallback':'Unavailable'];}))}`;
 if(syncMarkup(root,`<div class="sf-analysis-grid"><section class="sf-pane">${imagery}</section><section class="sf-pane">${prob}${details}<details data-section="audit"><summary>WXF Model &amp; Database</summary><div>${diagnostics()}</div></details></section></div>`,signature)){
 const s=root.querySelector('[data-sf-channel]');if(s)s.value=mode;renderFrame();}
 load().catch(()=>{});
}
function usableFrames(id){const primary=mode==='pair'?'continuum':mode;return A(data?.imagery?.channels?.[primary]).filter(f=>f.regions?.[id]&&fresh(f.observed_at,72));}
function renderFrame(){const host=document.querySelector('#fdFlareAnalysis [data-sf-images]');if(!host)return;const id=selected(),frames=usableFrames(id);if(!frames.length){host.innerHTML='<div class="sf-empty">Imagery Unavailable</div>';for(const x of document.querySelectorAll('[data-sf-frame],[data-sf-play]'))x.disabled=true;return;}for(const x of document.querySelectorAll('[data-sf-frame],[data-sf-play]'))x.disabled=false;
 if(frameIndex<0||frameIndex>=frames.length)frameIndex=frames.length-1;const frame=frames[frameIndex],keys=mode==='pair'?['continuum','magnetogram']:[mode];const selectedFrames=keys.map(k=>({key:k,frame:A(data.imagery.channels[k]).filter(f=>f.regions?.[id]).sort((a,b)=>Math.abs(time(a.observed_at)-time(frame.observed_at))-Math.abs(time(b.observed_at)-time(frame.observed_at)))[0]})).filter(x=>x.frame&&Math.abs(time(x.frame.observed_at)-time(frame.observed_at))<=3600000);
 host.className='sf-images'+(selectedFrames.length===1?' single':'');host.innerHTML=selectedFrames.map(x=>`<figure><div class="sf-image-box" style="--sf-zoom:${zoom}"><img src="${E(safeAsset(x.frame.regions[id].image))}" alt="${E(channelNames[x.key]+' '+id)}" data-native-pixels="${x.frame.regions[id].native_crop_pixels}"></div><figcaption>${E(channelNames[x.key])}<br>${date(x.frame.observed_at)}</figcaption></figure>`).join('');
 host.querySelectorAll('img').forEach(img=>img.onerror=()=>{img.replaceWith(Object.assign(document.createElement('div'),{className:'sf-empty',textContent:'Unavailable'}));});
 const range=document.querySelector('[data-sf-frame]');if(range){range.max=String(frames.length-1);range.value=String(frameIndex);}const count=document.querySelector('[data-sf-frame-count]');if(count)count.textContent=`${frameIndex+1} / ${frames.length}`;
 const status=document.querySelector('[data-sf-image-status]');if(status)status.textContent=`${num(frame.regions[id].native_crop_pixels,0)} Native Pixels · ${num(frame.pixel_scale_arcsec,3)}″/Pixel${fresh(frame.observed_at,12)?'':' · Older Image'}`;
}
function stopLoop(){clearInterval(loop);loop=0;const b=document.querySelector('[data-sf-play]');if(b)b.textContent='▶';}
function renderAll(){scheduled=0;renderBrowser();renderAnalysis();}
function queue(){if(!scheduled)scheduled=requestAnimationFrame(renderAll);}
async function load(force=false){if(pending)return pending;if(!force&&Date.now()-checked<300000)return data;checked=Date.now();pending=(async()=>{try{const response=await fetch(FEED+'latest.json?slot='+Math.floor(Date.now()/300000),{credentials:'omit',cache:'no-store',signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('Unavailable');const v=await response.json();if(v.schema!=='solar-flare-evidence-v1'||!fresh(v.checked_at,36))throw Error('Unavailable');data=v;error='';}catch(e){error='Unavailable';if(data&&!fresh(data.checked_at,36))data=null;}try{esa=await window.SpaceWxSolarEvidence?.load(force)||esa;}catch{}finally{pending=null;queue();}return data;})();return pending;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-sf-region],[data-sf-refresh],[data-sf-play],[data-sf-catalog],[data-sf-zoom]');if(!b)return;
 if(b.hasAttribute('data-sf-zoom')){zoom=zoom===1?2:1;b.textContent='Zoom '+zoom+'×';renderFrame();return;}
 if(b.dataset.sfRegion)selectRegion(b.dataset.sfRegion);else if(b.hasAttribute('data-sf-refresh')){load(true);window.dispatchEvent(new CustomEvent('spacewx:external-flare'));}else if(b.hasAttribute('data-sf-play')){if(loop)stopLoop();else{b.textContent='❚❚';loop=setInterval(()=>{if(!document.querySelector('[data-sf-images]')||document.visibilityState==='hidden'){stopLoop();return;}const n=usableFrames(selected()).length;if(n){frameIndex=(frameIndex+1)%n;renderFrame();}},900);}}else if(b.dataset.sfCatalog)document.querySelector('[data-fd-product="'+b.dataset.sfCatalog+'"]')?.click();});
document.addEventListener('change',e=>{if(e.target.matches('[data-sf-channel]')){mode=e.target.value;frameIndex=-1;renderFrame();}});
document.addEventListener('input',e=>{if(e.target.matches('[data-sf-frame]')){stopLoop();frameIndex=Number(e.target.value);renderFrame();}});
window.addEventListener('spacewxops:flare-guidance',queue);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopLoop();});
setInterval(()=>{if(document.querySelector('#fdFlareAnalysis'))load();else stopLoop();},300000);
window.SpaceWxFlareWorkspace={version:'2026.09.27.1',renderBrowser,renderAnalysis,load,stop:stopLoop,api:{region,date,fresh,modelMember,safeAsset,currentRegions},get data(){return data;}};
})();
